SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE DATABASE IF NOT EXISTS merit_capital CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE merit_capital;

-- Users
CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  email VARCHAR(191) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  full_name VARCHAR(191) NOT NULL,
  role ENUM('admin','mentor','investor','entrepreneur') NOT NULL DEFAULT 'entrepreneur',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  avatar_url VARCHAR(512) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Projects
CREATE TABLE IF NOT EXISTS projects (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  owner_id BIGINT UNSIGNED NULL,
  name VARCHAR(191) NOT NULL,
  description TEXT NULL,
  stage ENUM('Idea','MVP','Growth','Scale') DEFAULT 'Idea',
  industry VARCHAR(128) NULL,
  status ENUM('Active','Paused','Archived') DEFAULT 'Active',
  revenue_text VARCHAR(64) NULL,
  last_updated DATE NULL,
  image_url VARCHAR(512) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_projects_owner FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS project_tags (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  project_id BIGINT UNSIGNED NOT NULL,
  tag VARCHAR(64) NOT NULL,
  CONSTRAINT fk_project_tags_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
  INDEX(project_id), INDEX(tag)
) ENGINE=InnoDB;

-- CRAT
CREATE TABLE IF NOT EXISTS crat_domains (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(128) NOT NULL UNIQUE,
  display_order INT NOT NULL DEFAULT 0
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS crat_questions (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  domain_id BIGINT UNSIGNED NOT NULL,
  section_title VARCHAR(191) NOT NULL,
  sub_domain VARCHAR(191) NOT NULL,
  question_text VARCHAR(512) NOT NULL,
  attach_hint VARCHAR(255) NULL,
  display_order INT NOT NULL DEFAULT 0,
  CONSTRAINT fk_crat_questions_domain FOREIGN KEY (domain_id) REFERENCES crat_domains(id) ON DELETE CASCADE,
  INDEX(domain_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS crat_assessments (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  project_id BIGINT UNSIGNED NOT NULL,
  created_by BIGINT UNSIGNED NULL,
  status ENUM('in_progress','submitted','scored') DEFAULT 'in_progress',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_crat_assessments_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_crat_assessments_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS crat_answers (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  assessment_id BIGINT UNSIGNED NOT NULL,
  question_id BIGINT UNSIGNED NOT NULL,
  rating ENUM('yes','maybe','no') NULL,
  score TINYINT UNSIGNED NULL,
  attachment_name VARCHAR(255) NULL,
  attachment_url VARCHAR(512) NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_crat_answers_assessment FOREIGN KEY (assessment_id) REFERENCES crat_assessments(id) ON DELETE CASCADE,
  CONSTRAINT fk_crat_answers_question FOREIGN KEY (question_id) REFERENCES crat_questions(id) ON DELETE CASCADE,
  UNIQUE KEY uk_crat_answer (assessment_id, question_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS crat_domain_scores (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  assessment_id BIGINT UNSIGNED NOT NULL,
  domain_id BIGINT UNSIGNED NOT NULL,
  actual_score INT NOT NULL DEFAULT 0,
  target_score INT NOT NULL DEFAULT 0,
  readiness_pct DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  CONSTRAINT fk_crat_score_assessment FOREIGN KEY (assessment_id) REFERENCES crat_assessments(id) ON DELETE CASCADE,
  CONSTRAINT fk_crat_score_domain FOREIGN KEY (domain_id) REFERENCES crat_domains(id) ON DELETE CASCADE,
  UNIQUE KEY uk_crat_score (assessment_id, domain_id)
) ENGINE=InnoDB;

-- Chats
CREATE TABLE IF NOT EXISTS chats (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(191) NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_chats_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS chat_participants (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  chat_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  role ENUM('owner','member') DEFAULT 'member',
  added_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_cp_chat FOREIGN KEY (chat_id) REFERENCES chats(id) ON DELETE CASCADE,
  CONSTRAINT fk_cp_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  UNIQUE KEY uk_chat_user (chat_id, user_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS chat_messages (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  chat_id BIGINT UNSIGNED NOT NULL,
  sender_id BIGINT UNSIGNED NULL,
  content TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_cm_chat FOREIGN KEY (chat_id) REFERENCES chats(id) ON DELETE CASCADE,
  CONSTRAINT fk_cm_sender FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE SET NULL,
  INDEX(chat_id, created_at)
) ENGINE=InnoDB;

-- Opportunities (basic table removed in favor of richer schema below)

-- Resources
CREATE TABLE IF NOT EXISTS resources (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  kind ENUM('learning','template') NOT NULL,
  title VARCHAR(191) NOT NULL,
  body TEXT NULL,
  url VARCHAR(512) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Mentors
CREATE TABLE IF NOT EXISTS mentors (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  expertise VARCHAR(255) NULL,
  bio TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_mentors_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Investors
CREATE TABLE IF NOT EXISTS investors (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  firm VARCHAR(191) NULL,
  focus VARCHAR(255) NULL,
  verified TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_investors_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Startups
CREATE TABLE IF NOT EXISTS startups (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NULL,
  name VARCHAR(191) NOT NULL,
  sector VARCHAR(128) NULL,
  stage VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_startups_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Success Stories
CREATE TABLE IF NOT EXISTS success_stories (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(191) NOT NULL,
  summary TEXT NULL,
  image_url VARCHAR(512) NULL,
  link VARCHAR(512) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Notifications
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(191) NOT NULL,
  body TEXT NULL,
  `read` TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Sessions (DB-backed auth sessions)
CREATE TABLE IF NOT EXISTS sessions (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  token VARCHAR(128) NOT NULL UNIQUE,
  user_agent VARCHAR(255) NULL,
  ip VARCHAR(64) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at DATETIME NULL,
  CONSTRAINT fk_sessions_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX(user_id)
) ENGINE=InnoDB;

-- Password resets
CREATE TABLE IF NOT EXISTS password_resets (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  token VARCHAR(128) NOT NULL UNIQUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at DATETIME NOT NULL,
  used_at DATETIME NULL,
  CONSTRAINT fk_pwreset_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX(user_id), INDEX(token)
) ENGINE=InnoDB;

-- Project Reviews
CREATE TABLE IF NOT EXISTS project_reviews (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  project_id BIGINT UNSIGNED NOT NULL,
  reviewer_user_id BIGINT UNSIGNED NOT NULL,
  decision ENUM('approve','reject') NOT NULL,
  notes TEXT NULL,
  decided_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_proj_reviews_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_proj_reviews_user FOREIGN KEY (reviewer_user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Project Mentor Assignments
CREATE TABLE IF NOT EXISTS project_mentor_assignments (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  project_id BIGINT UNSIGNED NOT NULL,
  mentor_user_id BIGINT UNSIGNED NOT NULL,
  assigned_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_proj_assign_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
  CONSTRAINT fk_proj_assign_mentor FOREIGN KEY (mentor_user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Investments
CREATE TABLE IF NOT EXISTS investments (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  investor_user_id BIGINT UNSIGNED NOT NULL,
  startup_id BIGINT UNSIGNED NOT NULL,
  amount_text VARCHAR(64) NULL,
  note TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_inv_user FOREIGN KEY (investor_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_inv_startup FOREIGN KEY (startup_id) REFERENCES startups(id) ON DELETE CASCADE,
  INDEX(investor_user_id), INDEX(startup_id)
) ENGINE=InnoDB;

-- Opportunities
CREATE TABLE IF NOT EXISTS opportunities (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(191) NOT NULL,
  company VARCHAR(191) NOT NULL,
  description TEXT NOT NULL,
  location VARCHAR(191) NOT NULL,
  type ENUM('Funding Round','Partnership','Investment','Acquisition','Merger') NOT NULL,
  industry VARCHAR(128) NOT NULL,
  deadline DATETIME NOT NULL,
  postedDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  image VARCHAR(512) NULL,
  status ENUM('Open','Closing Soon','Closed') NOT NULL DEFAULT 'Open',
  amount VARCHAR(64) NOT NULL,
  stage VARCHAR(64) NOT NULL,
  equity VARCHAR(32) NULL,
  tags JSON NULL,
  investors JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Programs
CREATE TABLE IF NOT EXISTS programs (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(191) NOT NULL,
  description TEXT NOT NULL,
  duration VARCHAR(64) NOT NULL,
  startDate DATETIME NOT NULL,
  endDate DATETIME NOT NULL,
  organization VARCHAR(191) NOT NULL,
  imageUrl VARCHAR(512) NULL,
  enrolled BOOLEAN NOT NULL DEFAULT FALSE,
  closed BOOLEAN NOT NULL DEFAULT FALSE,
  tags JSON NULL,
  industry VARCHAR(128) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Lessons
CREATE TABLE IF NOT EXISTS lessons (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(191) NOT NULL,
  instructor VARCHAR(191) NOT NULL,
  duration VARCHAR(32) NOT NULL,
  imageUrl VARCHAR(512) NULL,
  views INT NOT NULL DEFAULT 0,
  industry VARCHAR(128) NOT NULL,
  description TEXT NOT NULL,
  tags JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
